language: php

php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - composer self-update --no-interaction
  - composer install --no-interaction
  - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php vendor/bin/grumphp run; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then php vendor/bin/phpunit; fi


