language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update --no-interaction
  - composer install --no-interaction
  - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

script:
  - php vendor/bin/grumphp run
